language: ruby
cache: bundler
rvm:
- 2.1

install: script/install-hunspell.sh

before_script:
- sudo git clean -df
- bundle update

script: rake test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
