language: ruby
cache: bundler
rvm: 2.2
sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y dpkg-dev devscripts dh-autoreconf
  - script/install-hunspell.sh

before_script:
  - sudo git clean -df

script:
  - bundle exec rake test

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
