# Site settings
title: GPA-Central Texas
email: webmaster@gpa-centex.org
description: "Adopting retired racing greyhounds in Austin, Texas and surrounding areas"
baseurl: "http://gpa-centex.org"
url: "http://gpa-centex.org"
twitter_username: GPA_CenTex

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
