# Site settings
title: GPA Central Texas
email: your-email@gpa-centex.com
description: "Adopting retired racing greyhounds in Austin, Texas and surrounding areas"
baseurl: ""
url: "http://gpa-centex.org"
#twitter_username: gpa-centex

# Build settings
markdown: kramdown
permalink: pretty
